spring:
  datasource:
    url: jdbc:oracle:thin:@//database-1.czuc4meqeb9b.ap-northeast-2.rds.amazonaws.com:1521/testdb
    username: kun
    password: 1111
    driver-class-name: oracle.jdbc.OracleDriver  # Oracle JDBC ????

server:
  port: 8080

mybatis:
  mapper-locations: > 
    - classpath:mapper/**/*.xml
    - classpath*:mapper/**/*.xml
  type-aliases-package: >
    - kr.or.komca.foundation.jwt.domain
    - kr.or.komca.komcadatacore.dto
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL

jwt:
  secret: RGV2ZWxvcG1lbnQgU3ByaW5nIEJvb3QgSldUIFNlY3JldCBLZXkgZm9yIFNpZ25pbmcgVG9rZW5z
  access-token-validity: 1800    # 30? (? ??)
  refresh-token-validity: 10800  # 3?? (? ??)

# ?? ????? application.yml
foundation:
  security:
    standalone: true  # ?? ?????? ?? ??? ?? true

