jwt:
  secret: ${JWT_SECRET:RGV2ZWxvcG1lbnQgU3ByaW5nIEJvb3QgSldUIFNlY3JldCBLZXkgZm9yIFNpZ25pbmcgVG9rZW5z}
  access-token-validity: ${JWT_ACCESS_VALIDITY:1800}
  refresh-token-validity: ${JWT_REFRESH_VALIDITY:18000}